export const Colors = {
    light: {
        transparent: 'transparent',
        primaryBrown: '#343434',
        primarybrowntext:'#43484B',
        background: '#fff',
        icon: '#687076',
        tabIconDefault: '#687076',
        primaryBlue: '#10B981',
        lightPrimaryBlue: '#C7DAF9',
        lightBackground: '#E9F5F8',
        backgroundGray: '#F9F9FE',
        lightText: '#99A1B5',
        black: '#000000',
        primaryTextColor: '#000000',
        secondaryTextColor: '#5E5F6D',
        progress: '#10B981',
        red: 'red',
        lightGray: '#5A5A5A',
        whiteText: '#FEFEFE',
        white: '#FFFFFF',

    },
    dark: {
           primarybrowntext:'#43484B',
        transparent: 'transparent',
        text: '#ECEDEE',
        background: '#151718',
        icon: '#9BA1A6',
        tabIconDefault: '#9BA1A6',
        lightBackground: '#3A3B45',
        primaryBlue: '#ffffff',
        lightPrimaryBlue: '#C7DAF9',
        borderLightGray: '#E7EBF1',
        backgroundGray: '#F9F9FE',
        lightText: '#99A1B5',
        black: '#9BA1A6',
        primaryTextColor: '#FFFFFF',
        secondaryTextColor: '#FFFFFF',
        progress: '#105BD9',
        headerBg: '#151718',
        inputBorder: '#105BD9',
        lightGreen: '#E8FDF9',
        medGreen: '#30AF82',
        textBlack: '#000',
        dark100: '#202126',
        inputBg: '#262626'
    },
};